//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReaderObject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OracleEntities : DbContext
    {
        public OracleEntities()
            : base("name=OracleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COURS> COURS { get; set; }
        public virtual DbSet<EMPLOYE> EMPLOYE { get; set; }
        public virtual DbSet<INSCRIT> INSCRIT { get; set; }
        public virtual DbSet<PARTICIPER> PARTICIPER { get; set; }
        public virtual DbSet<PROJET> PROJET { get; set; }
        public virtual DbSet<SEMINAIRE> SEMINAIRE { get; set; }
    }
}
